plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.testng', name: 'testng', version: '7.1.0'
    implementation("io.github.bonigarcia:webdrivermanager:5.7.0")
    implementation("org.seleniumhq.selenium:selenium-java:4.26.0")
}

test {
    useTestNG()
}